---
name: build pandoc-slides

"on":
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - apko/pandoc-slides.yaml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  apko:
    name: build pandoc-slides
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      actions: read
    outputs:
      digest: ${{ steps.apko.outputs.digest }}
    steps:
      - name: checkout project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: apko snapshot
        id: apko
        uses: chainguard-images/actions/apko-snapshot@main
        with:
          config: apko/pandoc-slides.yaml
          base-tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          target-tag: devel
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          sbom-attest: true
          slsa-attest: true
  smoke:
    name: test pandoc-slides
    needs: apko
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        ce:
          - docker
          - podman
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: smoke test
        run: |
          set -x
          CE=${{ matrix.ce }} OCI=${{ needs.apko.outputs.digest }} make container
          CE=${{ matrix.ce }} make example
      - name: prepare html assets
        if: matrix.ce == 'docker'
        run: |
          set -x
          mkdir html/
          mv example.html html/index.html
          mv css/ pd-images/ media/ html/
      - uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595
        if: matrix.ce == 'docker'
        with:
          name: pandoc-slides-example
          path: html/
          if-no-files-found: error
          retention-days: 1
  publish:
    name: publish pandoc-slides
    needs: smoke
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110
        with:
          name: pandoc-slides-example
          path: html/
      - name: publish to gh-pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html/
      - name: install crane
        uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c
      # tag latest only after smoke tests
      - name: tag pandoc-slides (latest)
        run: |
          crane tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:devel" latest
